# Generated by Django 3.0.3 on 2020-04-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagePostIdsStr',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isImage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='textPostId',
        ),
    ]
