# Generated by Django 3.0.3 on 2020-03-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='https://spongebook.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='https://spongebook.herokuapp.com/'),
        ),
    ]
