# Generated by Django 3.0.3 on 2020-04-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200402_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='githubId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
