# Generated by Django 3.0.3 on 2020-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_githubid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='githubId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
