# Generated by Django 3.0.3 on 2020-03-26 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('U', 'Unprocessed'), ('A', 'Accepted'), ('R', 'Rejected')], default='U', max_length=1)),
                ('isCopy', models.BooleanField()),
            ],
        ),
    ]
