# Generated by Django 3.0.7 on 2020-07-08 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='f1Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f2friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='f2Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('f1Id', 'f2Id')},
        ),
    ]
