# Generated by Django 3.0.3 on 2020-04-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_node_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='shareImage',
            field=models.BooleanField(default=True),
        ),
    ]
