# Generated by Django 3.0.3 on 2020-04-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_node_shareimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
