# Generated by Django 3.0.3 on 2020-04-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='githubToken',
        ),
    ]
