# Generated by Django 3.0.7 on 2020-07-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_is_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approve',
            field=models.BooleanField(default=True),
        ),
    ]
