# Generated by Django 3.0.3 on 2020-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200320_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
